- template.yaml
adding DISCOVERYENDPOINT to all envs
- [F2F-450](https://govukverify.atlassian.net/browse/F2F-450)
[F2F-450]: https://govukverify.atlassian.net/browse/F2F-450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-450]: adding DISCOVERYENDPOINT to all envs

- README.md
- template.yaml
Container scaling settings updated to enable dynamic scaling
Ensure we can handle load peaks, make consistent with F2F and CIC.
- [F2F-606](https://govukverify.atlassian.net/browse/F2F-606)
[F2F-606]: https://govukverify.atlassian.net/browse/F2F-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-606 FE container scaling settings

- .github/workflows/pull-request-sonar.yml
- sonar-project.properties
- Add sonar scan properties on the front end repo.
- Add workflow to run the sonar scan on the pull request and merge
- Sonar workspace are already created and token are already done
- [F2F-604](https://govukverify.atlassian.net/browse/F2F-604)
[F2F-604]: https://govukverify.atlassian.net/browse/F2F-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-604: Add sonar scan to IPR Front end repo

- template.yaml
Created cloud watch alarms for monitoring IPR frontend. 
- FE5XXErrorAlarm
- FE4XXErrorAlarm
- FELatencyAlarmP95
- FELatencyAlarmP99
- FELowContainerTaskCountAlarm
- FEHighContainerTaskCountWarning
- FELowContainerTaskCountCritical
- WarningAlarmDashboard
- CriticalAlarmDashboard
- [F2F-465](https://govukverify.atlassian.net/browse/F2F-465)
[F2F-465]: https://govukverify.atlassian.net/browse/F2F-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-465: Implement Monitoring & Alerts for IPV Return Frontend

- template.yaml
Reverts govuk-one-login/ipvreturn-front#176
> Revert "IPS-476: Add step scaling policy and alarms"

- checkIpvResume.sh
- package.json
Add shell script to check /resume endpoint is operational and response received in 2.5 seconds
- [KIWI-1722](https://govukverify.atlassian.net/browse/KIWI-1722)
[KIWI-1722]: https://govukverify.atlassian.net/browse/KIWI-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add IPV Resume Shell Script Test

- .github/workflows/post-merge-push-test-container-to-build.yml
- .github/workflows/post-merge-push-test-container-to-dev.yml
- Dockerfile.test
- run-tests.sh
- Add the test container with build and push to the ECR and required workflows.
- Add the required secrets. 
- Added test container for testing the workflow
- Added run_test.sh to streamline the dockerbuild like other services
- Added the workflow for the test container for dev and build
- To add test conatainer workflow which builds and pushes the test container to the ECR
- [IPS-660](https://govukverify.atlassian.net/browse/IPS-660)
[IPS-660]: https://govukverify.atlassian.net/browse/IPS-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-660: Implement IPV Return frontend test container and workflows

- run-tests.sh
Update run-tests.sh to run check /resume shell script
- [IPS-660](https://govukverify.atlassian.net/browse/IPS-660)
[IPS-660]: https://govukverify.atlassian.net/browse/IPS-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update run-tests.sh to run check /resume shell script

- .secrets.baseline
- template.yaml
- Add new origin A record for integrating cloudFront
- Add new origin A record for integrating cloudFront
- [IPS-690](https://govukverify.atlassian.net/browse/IPS-690)
[IPS-690]: https://govukverify.atlassian.net/browse/IPS-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-690: Create DNS origin record for Cloufront

- .secrets.baseline
- template.yaml
- Add Cloudfront DNS name on dev to int environment
- Add WAf association on the frontend template
- Add Cloudfront DNS name to test on dev environment
- - Add WAf association on the frontend template
- Add Cloudfront DNS name to test on dev environment
- Add Cloudfront DNS name to test on dev environment
- - Add WAf association on the frontend template
- [IPS-734](https://govukverify.atlassian.net/browse/IPS-734)
[IPS-734]: https://govukverify.atlassian.net/browse/IPS-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-734: Add DNS switchover and WAF association

- .secrets.baseline
- template.yaml
- Prepration for CloudFront Go Line
- Deploy CloudFront stacks
- DNS switchover to the CF domain name
- Disable block WAF association
- DNS switchover to the CF domain name
- Disable block WAF association
- In order for go live
- Deploy CloudFront stacks
- [IPS-787](https://govukverify.atlassian.net/browse/IPS-787)
[IPS-787]: https://govukverify.atlassian.net/browse/IPS-787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-787: Deploy CloudFront on IPVReturn production environment

- .github/workflows/post-merge-actions-build.yml
- .github/workflows/post-merge-actions-dev.yml
- Update upload action ECR version from v1.2.1 to v1.2.4
- Update upload action ECR version from v1.2.1 to v1.2.4
- [IPS-838](https://govukverify.atlassian.net/browse/IPS-838)
[IPS-838]: https://govukverify.atlassian.net/browse/IPS-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-838: Update Upload action ECR version

- .github/workflows/post-merge-actions-dev.yml
- .secrets.baseline
- dev.Dockerfile
- template.yaml
- created dev dockerfile with arm64
- updated template ECS resources
- - updated workflows `post-merge-to-dev.yml`
- Migrate All Orange Dev Stubs and Front ends to ARM64 and spot Instances
- [IPS-227](https://govukverify.atlassian.net/browse/IPS-227)
[IPS-228]: https://govukverify.atlassian.net/browse/IPS-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-227]: https://govukverify.atlassian.net/browse/IPS-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-228 migrate frontend to ARM

- .pre-commit-config.yaml
- .secrets.baseline
- template.yaml
- Enable block WAF and associate with the load balancer
- Disable the count WAF which was deployed with the CloudFront
- Enable the block WAF 
- Associate the block with Load balancer
- Count WAF been added during CloudFront deployment.
- Having found CloudFront working, the count waf need to be disabled to enable the block WAF
- Disable the count association with Load balancer and enable the block waf association with load balancer
- Verify the CloudFront traffic using count WAF
- [IPS-740](https://govukverify.atlassian.net/browse/IPS-740)
[IPS-740]: https://govukverify.atlassian.net/browse/IPS-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-740: Enable block WAF association with Load balancer

- template.yaml
Canary deployment for ECS has 2 stages of deployment and should be deployed in stgaes. This is deployment stage 1 where additional target group is created for green deployment, configured to code deploy to deploy the blue green deployment. Additionally the ecs canary stack is deployed which in turn deploys a nested stack for canary deployment. Also, added alarms for rollback on canary deployments.
- ECS Canary Deployment on F2F CRI
- Added Canary deployment feature flat to deploy on Dev Environment
- Add deployment controller to deploy code or ecs
- Add Target group for green deployment
- Add canary deployment stack
- Add Load balancer 4xx and 5xx alarms
- Canary deployment feature implementation
- [IPS-561](https://govukverify.atlassian.net/browse/IPS-561)
[IPS-561]: …
> IPS-561: Canary Deployment on IPVReturn - Step 1 deployment

- .github/workflows/pull-request-sonar.yml
- sonar-project.properties
Updated to report to correct Sonar instance
In oder to send reports to the correct place for analysis
- [KIWI-1958](https://govukverify.atlassian.net/browse/KIWI-1958)
[KIWI-1958]: https://govukverify.atlassian.net/browse/KIWI-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1958] - | Platform | Change to new OL Sonar Organisation

- .github/workflows/post-merge-checks.yml
- .github/workflows/pull-request-sonar.yml
- sonar-project.properties
Added sonar checks to pull requests
Added sonar checks to post merge
To a allow better monitoring of the IPV return CRI
> KIWI-1958: Added sonar checks to pull request and post merge

- Dockerfile
- dev.Dockerfile
- src/Index.ts
- src/Routes.ts
- template.yaml
- Configured AWS ECS healthchecks in template
- Updated Dockerfile to reference healthcheck
> KIWI-2135 - Configuring ECS Healthchecks

- .github/workflows/post-merge-checks.yml
Updated post-merge-check yml to fix npm lint error
To fix post-merge-check workflow failure
> Fix post merge check

- Dockerfile.test
- samconfig.toml
- template.yaml
- [KIWI-2448](https://govukverify.atlassian.net/browse/KIWI-2448)
[KIWI-2448]: https://govukverify.atlassian.net/browse/KIWI-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2448] - IPR | FE | Investigate cause of blocked FE pipeline
